### ISSUE TITLE
Get started videos - not working

### ISSUE THREAD

**Issue by TabtIrummet** [Difference/LCCbygBase#111]
On the Hjælp tab – kom godt igang , none of the videos work.

**Comment by Difference** [comment]
Fixed by inserting <meta http-equiv="X-UA-Compatible" content="IE=11" />  into theme on lccbyg.dk/help pages, making LCCbyg use a newer version/rendering mode of the WPF webbrowser plugin.
This fix also targets older installations og LCCbyg thta was also affected. Error maybe related to changing lccbyg.dk protocol to https.
